#
# lazygit config
#
# See:
#   - https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
#
# @todo link or move this file
#

git:
  # https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  paging:
    colorArg: always
    # https://github.com/jesseduffield/lazygit/issues/1688#issuecomment-1281220782
    pager: delta --paging=never --true-color=never
gui:
  showIcons: true
os:
  # editorCommand: 'code' # default: $(git config core.editor)
  editCommandTemplate: "{{editor}} --goto -- {{filename}}:{{line}}" # code
  # editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}' # vim
