# Taps: brew tap
tap homebrew/cask

# Brews: brew install
brew git
brew htop
brew jq
brew mas
brew python
brew pyenv
brew rg
brew shellcheck
brew tmux

# Apps: brew install --cask
cask copyq
cask iterm2
cask rectangle
cask spotify
cask sublime-text
cask visual-studio-code
cask zoomus

# App Store
# appstore 803453959 Slack
