# Brews
brew "git"
brew "htop"
brew "jq"
brew "mas"
brew "python"
brew "pyenv"
brew "rg"
brew "shellcheck"
brew "tmux"

# Applications
cask "copyq"
cask "iterm2"
cask "rectangle"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
cask "zoomus"

# App Store
# mas "Slack", id: 803453959
