#!/usr/bin/env zsh

# https://github.com/romkatv/zsh4humans/blob/v5/tips.md#fzf
local i
for i in {0..255}; do
    print -Pn \
        "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " \
        ${${(M)$((i%6)):#3}:+$'\n'}
done

# local c
# for c in {0..255}; do
#     tput setab "$c"
#     echo -n "$c "
# done
# tput sgr0
# echo

# local x=$(tput op)
# local y=$(printf %76s)
# local i o
# for i in {0..255}; do
#     o=00$i
#     echo -e "${o:${#o}-3:3}" "$(
#         tput setaf "$i"
#         tput setab "$i"
#     )${y// /=}$x"
# done
