#!/usr/bin/env zsh

# https://github.com/romkatv/zsh4humans/blob/v5/tips.md#fzf
for i in {0..255}; do
    print -Pn \
        "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " \
        ${${(M)$((i%6)):#3}:+$'\n'}
done

# for C in {0..255}; do
#     tput setab "$C"
#     echo -n "$C "
# done
# tput sgr0
# echo

# x=$(tput op)
# y=$(printf %76s)
# for i in {0..255}; do
#     o=00$i
#     echo -e "${o:${#o}-3:3}" "$(
#         tput setaf "$i"
#         tput setab "$i"
#     )${y// /=}$x"
# done
