#!/usr/bin/env zsh
# shellcheck shell=bash

# Sets the cursor mode based on the current keymap.
#
# See:
#  - https://thevaluable.dev/zsh-install-configure-mouseless/
#  - https://unix.stackexchange.com/questions/547/make-my-zsh-prompt-show-mode-in-vi-mode
#
# For cursor shapes, see:
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vi-mode#cursor-styles
case $KEYMAP in
vicmd) echo -ne '\e[1 q' ;;                  # blinking block
main | viins | command) echo -ne '\e[5 q' ;; # blinking beam
visual) echo -ne '\e[2 q' ;;                 # block
isearch | *) echo -ne '\e[3 q' ;;            # blinking underline
esac
