#!/usr/bin/env zsh

# Generates an init script that loads the given plugin(s) and prints it for
# sourcing. This helper is only meant to be called from load-plugins, or for
# debugging.
#
# Sources:
#  - https://github.com/mattmc3/zsh_unplugged/blob/main/antidote.lite.zsh
#  - https://github.com/sorin-ionescu/prezto/blob/master/init.zsh

emulate -L zsh
setopt extendedglob globdots

local plugin init init_dir
local inits=()
local funcs=()
for plugin in $@; do
    # Find the plugin init script or functions dir.
    inits=(
        $ZPLUGINDIR/$plugin/${plugin:t}.{plugin.zsh,zsh-theme,zsh,sh}(.N)
        $ZPLUGINDIR/$plugin/*.{plugin.zsh,zsh-theme,zsh,sh}(.N)
        $ZPLUGINDIR/$plugin(.N)
        $plugin/*.{plugin.zsh,zsh-theme,zsh,sh}(.N)
        $plugin(.N)
        $ZPLUGINDIR/$plugin/functions(/FN)
        $plugin/functions(/FN)
    )
    if (($#inits == 0)); then
        printf '[error] Plugin not found: %s' $plugin >&2
        continue
    fi

    init=${inits[1]}
    init_dir=${init:h}

    # Prepend functions to fpath and autoload them.
    funcs=($init_dir/functions/^([_.]*|prompt_*_setup|README*|*~)(.N:t))
    if (($#funcs > 0)); then
        echo "fpath=($init_dir/functions \$fpath)"
        echo autoload -Uz $funcs
    fi

    # Source the plugin.
    if [ -r $init ]; then
        echo "source:file $init"
    fi
done
