# btop
['.config/btop/themes']
type = 'archive'
url = 'https://git.sr.ht/~blueingreen/base16-btop/archive/main.tar.gz'
exact = true
stripComponents = 2
refreshPeriod = '168h'
include = ['*/colors/**']
