#
# prezto
#

['.local/share/zsh-plugins/prezto']
type = 'archive'
url = 'https://github.com/sorin-ionescu/prezto/archive/master.tar.gz'
exact = true
stripComponents = 2
refreshPeriod = '168h'
include = ['*/modules/**']

['.local/share/zsh-plugins/prezto/autosuggestions/external']
type = 'archive'
url = 'https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
exclude = ['*/.*']

['.local/share/zsh-plugins/prezto/completion/external']
type = 'archive'
url = 'https://github.com/zsh-users/zsh-completions/archive/master.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
exclude = ['*/.*']

['.local/share/zsh-plugins/prezto/history-substring-search/external']
type = 'archive'
url = 'https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
exclude = ['*/.*']

['.local/share/zsh-plugins/powerlevel10k']
type = 'archive'
url = 'https://github.com/romkatv/powerlevel10k/archive/master.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
exclude = ['*/*.png', '*/gitstatus/src', '**/.*']

['.local/share/zsh-plugins/prezto/syntax-highlighting/external']
type = 'archive'
url = 'https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
exclude = [
    '*/.editorconfig',
    '*/.git*',
    '*/highlighters/**/test-data',
    '*/images',
    '*/tests',
]

#
# Other
#

['.local/share/zsh-plugins/zsh-autocomplete']
type = 'archive'
url = 'https://github.com/marlonrichert/zsh-autocomplete/archive/main.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
exclude = ['*/.*', '*/Tests']

['.local/share/zsh-plugins/zsh-autopair']
type = 'archive'
url = 'https://github.com/hlissner/zsh-autopair/archive/master.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
exclude = ['*/.*', '*/tests']

['.local/share/zsh-plugins/fzf-tab']
type = 'archive'
url = 'https://github.com/Aloxaf/fzf-tab/archive/master.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
exclude = ['**/.*', '*/test']
