#!/usr/bin/env zsh
# shellcheck shell=bash

#
# Generated by build-load-plugins.zsh.
#
# load-plugins.zsh: loads the configured zsh plugins. Should be called by
# ~/.zshrc.
#

emulate -LR zsh
setopt nomonitor

# Define pmodload as a no-op because prezto modules call it to load prereq
# modules. This means the order of modules in $plugins is extra important.
echo pmodload() { }

source:file /Users/alexforsythe/.zpreztorc
fpath=($ZPLUGINDIR/prezto/helper/functions $fpath)
autoload -Uz add-zsh-trap escape-eval
source:file $ZPLUGINDIR/prezto/helper/init.zsh
source:file $ZPLUGINDIR/prezto/environment/init.zsh
source:file $ZPLUGINDIR/prezto/spectrum/init.zsh
source:file $ZPLUGINDIR/prezto/gnu-utility/init.zsh
fpath=($ZPLUGINDIR/prezto/utility/functions $fpath)
autoload -Uz diff dut make prep psub wdiff zsh-help
source:file $ZPLUGINDIR/prezto/utility/init.zsh
fpath=($ZPLUGINDIR/prezto/archive/functions $fpath)
autoload -Uz archive lsarchive unarchive
source:file $ZPLUGINDIR/prezto/archive/functions
source:file $ZPLUGINDIR/prezto/editor/init.zsh
fpath=($ZPLUGINDIR/prezto/git/functions $fpath)
autoload -Uz git-branch-current git-commit-lost git-dir git-hub-browse git-hub-shorten-url git-info git-root git-stash-clear-interactive git-stash-dropped git-stash-recover git-submodule-move git-submodule-remove
source:file $ZPLUGINDIR/prezto/git/alias.zsh
source:file $ZPLUGINDIR/zsh-completions/zsh-completions.plugin.zsh
source:file $ZPLUGINDIR/external-completions/external-completions.plugin.zsh
source:file $ZPLUGINDIR/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source:file $ZPLUGINDIR/prezto/history/init.zsh
source:file $ZPLUGINDIR/prezto/syntax-highlighting/init.zsh
source:file $ZPLUGINDIR/prezto/history-substring-search/init.zsh
source:file $ZPLUGINDIR/prezto/autosuggestions/init.zsh
source:file $ZPLUGINDIR/prezto/directory/init.zsh
source:file $ZPLUGINDIR/prezto/command-not-found/init.zsh
source:file $ZPLUGINDIR/prezto/ssh/init.zsh
source:file $ZPLUGINDIR/prezto/docker/alias.zsh
source:file $ZPLUGINDIR/select-bracketed/select-bracketed.plugin.zsh
source:file $ZPLUGINDIR/select-quoted/select-quoted.plugin.zsh
source:file $ZPLUGINDIR/vim-surround/vim-surround.plugin.zsh
source:file $ZPLUGINDIR/run-help/run-help.plugin.zsh
source:file $ZPLUGINDIR/powerlevel10k/powerlevel10k.zsh-theme

# Remove pmodload now that all prezto modules have been loaded.
unfunction pmodload
