#!/usr/bin/env zsh
# shellcheck shell=bash

set -e

emulate -LR zsh
setopt extendedglob globdots

#
# build.zsh: generates scripts to be sourced by ~/.zshrc and compiles them, the
# zsh completions dump, plugins, and plugin functions.
#
#  - This script runs automatically after each call to `chezmoi apply`, which
#    ensures that generated scripts stay up-to-date
#  - Generating script files makes them easier to debug and avoids the need to
#    `eval` command output, which can slow down shell startup
#  - Compiling scripts and function digests reduces shell startup time
#

autoload -Uz zrecompile

gen_dir=$XDG_CONFIG_HOME/shell/zsh/gen
load_plugins=$gen_dir/load-plugins.zsh
init_commands=$gen_dir/init-commands.zsh

# Load $plugins.
source "$XDG_CONFIG_HOME/shell/zsh/plugins.zsh"

# Returns the init script for the given plugin. $plugin can be an absolute path
# or relative path in $ZPLUGINDIR to a script, functions dir, or dir containing
# a script and/or functions dir.
#
# Usage: r_plugin_init $rval_name $plugin
r_plugin_init() {
    # The plugin name or anything not containing "test"
    filenames="${2:t}|^*test*"
    # Valid extensions for the init file.
    exts="plugin.zsh|zsh-theme|zsh|sh"
    # Don't use short-ciruit mode (Y1) because it changes the order.
    print -v $1 -- {$ZPLUGINDIR/$2/($~filenames).($~exts),$2/($~filenames).($~exts),$2}(.N[1])
    # matches=({$ZPLUGINDIR/,}$2{/{${2:t},^*test*}.{plugin.zsh,zsh-theme,zsh,sh},}(.N))
    # print -v $1 $matches[1]
}

# Returns the functions directory for the given plugin. $plugin can be an
# absolute path or relative path in $ZPLUGINDIR to a dir containing a functions
# dir, or a functions dir.
#
# Usage: r_plugin_funcs_dir $rval_name $plugin
r_plugin_funcs_dir() {
    if [[ ${2:t} == functions ]]; then
        print -v $1 -- {$ZPLUGINDIR/,}$2/*(.NY1:h)
    else
        print -v $1 -- {$ZPLUGINDIR/,}$2/functions/*(.NY1:h)
    fi
}

# Returns an array of paths to all autoloadable functions in the given
# directory.
#
# Usage: r_autoloadable_funcs $rval_name $funcs_dir
r_autoloadable_funcs() {
    # Use eval here because print -v converts the array to a string.
    eval "$1=($2/^([_.]*|prompt_*_setup|README*|*~)(.N))"
}

# Generates an init script that loads the given plugin(s) and prints it for
# sourcing. This helper is only meant to be called from load-plugins, or for
# debugging.
#
# Sources:
#  - https://github.com/mattmc3/zsh_unplugged/blob/main/antidote.lite.zsh
#  - https://github.com/sorin-ionescu/prezto/blob/master/init.zsh
print-load-plugins() {
    cat <<EOF
#!/usr/bin/env zsh
# shellcheck shell=bash

#
# Generated by build-load-plugins.zsh.
#
# load-plugins.zsh: loads the configured zsh plugins. Should be called by
# ~/.zshrc.
#

# Define pmodload as a no-op because prezto modules call it to load prereq
# modules. This means the order of modules in \$plugins is extra important.
pmodload() { }

EOF
    for plugin in $@; do
        r_plugin_init init $plugin
        r_plugin_funcs_dir funcs_dir $plugin
        if [[ -z $init && -z $funcs_dir ]]; then
            printf "%s\n" "Plugin not found: $plugin" >&2
            continue
        fi

        # Prepend plugin functions to fpath and autoload them.
        if [[ -n $funcs_dir ]]; then
            printf "%s\n" "fpath=(${funcs_dir/$ZPLUGINDIR/\$ZPLUGINDIR} \$fpath)"
            r_autoloadable_funcs funcs $funcs_dir
            if (($#funcs > 0)); then
                printf "%s\n" "autoload -Uz ${(j: :)funcs[@]:t}"
            fi
        fi

        # Source the plugin.
        if [[ -n $init ]]; then
            printf "%s\n" "source:file ${init/$ZPLUGINDIR/\$ZPLUGINDIR}"
        fi
    done
    cat <<EOF

# Remove pmodload now that all prezto modules have been loaded.
unfunction pmodload
EOF
}

# Generates a script that initializes commands requiring extra setup and prints
# it for sourcing. This helper is only meant to be called from init-commands, or
# for debugging.
print-init-commands() {
    cat <<EOF
#!/usr/bin/env zsh
# shellcheck shell=bash

#
# Generated by build-init-commands.zsh.
#
# init-commands.zsh: initializes commands that require extra setup in every
# shell. Should be called by ~/.zshrc.
#

EOF

    if hash mise >/dev/null 2>&1; then
        # Make sure mise is deactivated first, otherwise `activate` will print
        # deactivation commands.
        mise deactivate >/dev/null 2>&1

        printf '# mise\n\n'
        mise activate zsh
        printf '\n'
    fi

    # @audit completion not working, just lists dirs like cd
    if hash zoxide >/dev/null 2>&1; then
        printf '# zoxide (load after compinit, fzf-rc, zsh-autocomplete)\n\n'
        zoxide init zsh
        printf '\n'
    fi
}

# Generate and compile scripts.
mkdir -p $gen_dir
print-load-plugins $plugins >$load_plugins
zrecompile -p -U -R $load_plugins
print-init-commands >$init_commands
zrecompile -p -U -R $init_commands

# Recompile zsh completions dump.
#  - -p: required to create/add new functions to the digest
#  - -U: suppress alias expansion
#  - -M: enables memory-mapping so multiple zsh processes can share the digest
zrecompile -p -U -M "$ZSH_COMPDUMP"

# Recompile zsh plugins and their function digests.
for plugin in $plugins; do
    r_plugin_init init $plugin
    r_plugin_funcs_dir funcs_dir $plugin
    if [[ -z $init && -z $funcs_dir ]]; then
        printf "%s\n" "Plugin not found: $plugin" >&2
        return 1
    fi

    # -R prevents the contents from being memory-mapped (i.e. shared between
    # shells), which is preferred for scripts.
    zrecompile -p -U -R $init

    if [[ -n $funcs_dir ]]; then
        r_autoloadable_funcs autoloadable_funcs $funcs_dir
        if (($#autoloadable_funcs > 0)); then
            zrecompile -p -U $funcs_dir ${autoloadable_funcs[@]}
        fi
    fi
done
