#!/usr/bin/env bash

#
# ~/.bashrc: sourced by bash in interactive non-login shells
#
# https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
#

#
# Profile
#
# ~/.bash_profile isn't sourced by non-login shells, so load the shared profile
# config here.
#

# Load env.sh and brew-shellenv first, which are required by profile.sh.
_envrc="$XDG_CONFIG_HOME/shell/env.sh"
# shellcheck source=src/dot_config/shell/env.sh
if [ ! -r "$_envrc" ] || ! source "$_envrc"; then
    printf '[error] %s\n' "file not loaded: $_envrc" >&2
    return 1
fi

# Set homebrew prefix and add bins to path.
if hash brew >/dev/null 2>&1; then
    eval "$(brew shellenv bash)"
fi

_profile="$XDG_CONFIG_HOME/shell/profile.sh"
# shellcheck source=src/dot_config/shell/profile.sh
if [ ! -r "$_profile" ] || ! source "$_profile"; then
    printf '[error] %s\n' "file not loaded: $_profile" >&2
    return 1
fi
log:debug "file loaded: $_envrc"
log:debug "file loaded: $_profile"
unset _envrc _profile

#
# Options
#

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

#
# Prompt
#

# Set variable identifying the chroot you work in (used in the prompt below).
if [[ -z ${debian_chroot:-} && -r /etc/debian_chroot ]]; then
    debian_chroot=$(</etc/debian_chroot)
fi

# Set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
xterm-color* | xterm-256color* | tmux*)
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    ;&
xterm* | rxvt*)
    # If this is an xterm set the title to user@host:dir
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*) PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ ' ;;
esac

#
# Completions
#

# brew
if ! shopt -oq posix; then
    source:file "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
fi

# git
source:file "$XDG_DATA_HOME/bash-plugins/external-completions/git-completion.bash"

# gcloud
source:file "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.bash.inc"

#
# Plugins
#

# fzf: https://thevaluable.dev/fzf-shell-integration/
if [ -n "$FZF_DIR" ] && iscmd fzf; then
    source:file "$XDG_CONFIG_HOME/shell/fzf.sh"
    source:file "$FZF_DIR/shell/completion.bash"
    source:file "$FZF_DIR/shell/key-bindings.bash"
fi

# Use dircolors to set LS_COLORS to a nice theme (its output is the setter
# command).
#
# GNU ls (installed by brew as part of corutils on MacOS) uses LS_COLORS to
# colorize output. Here's a good reference:
# https://the.exa.website/docs/colour-themes
run:if-cmd gdircolors eval "$(gdircolors)"

#
# Aliases
#
# Load aliases last to override any conflicting ones defined by plugins.
#

source:file "$XDG_CONFIG_HOME/shell/aliases.sh"
if [ -r "$XDG_CONFIG_HOME/shell/workrc.sh" ]; then
    source:file "$XDG_CONFIG_HOME/shell/workrc.sh"
fi

#
# Hooks
#

eval:if-cmd mise eval mise activate bash
eval:if-cmd zoxide eval zoxide init bash
