#!/usr/bin/env zsh
# shellcheck shell=bash

#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
# { true; } &
# disown
