#!/usr/bin/env zsh
# shellcheck shell=bash

#
# ~/.zshrc: sourced in interactive shells
#
#  - Should set up options, key bindings, functions, aliases, etc.
#
# Guides:
#  - https://zsh.sourceforge.io/Intro/intro_3.html
#  - https://zsh.sourceforge.io/Guide/zshguide02.html
#
# Examples:
#  - https://github.com/zsh-users/zsh/blob/master/StartupFiles/zshrc
#  - https://github.com/marlonrichert/zsh-launchpad/tree/main
#  - https://github.com/romkatv/zsh4humans/blob/v5/.zshrc
#  - https://github.com/romkatv/zsh4humans/blob/v5/.zshrc.mac
#

# @note Uncomment the following line to profile startup time.
# zmodload zsh/zprof

# Load shared helpers (required by profile.sh).
rchelpers="${XDG_CONFIG_HOME:-$HOME/.config}/shell/helpers.sh"
# shellcheck disable=1090
if [ ! -r "$rchelpers" ] || ! source "$rchelpers"; then
    printf '[error] %s\n' "file not loaded: $rchelpers" >&2
    return 1
fi
log:debug "file loaded: $rchelpers"
unset rchelpers

# Load shared shell profile.
source:file "$XDG_CONFIG_HOME/shell/profile.sh"

#
# Options
#
#  - Should be set after loading plugins to avoid being overridden
#  - Reference: https://zsh.sourceforge.io/Doc/Release/Options.html
#  - Examples
#    - https://github.com/willghatch/zsh-saneopt/tree/master
#    - https://github.com/sorin-ionescu/prezto/tree/master/modules
#

# Correctly display UTF-8 with combining characters.
if [[ "$(locale LC_CTYPE)" == "UTF-8" ]]; then
  setopt combiningchars
fi

# Disable the log builtin so we don't conflict with /usr/bin/log, which is used
# for system logging on some OSes like MacOS.
disable log

export HISTSIZE=10000
export SAVEHIST=10000

# Use extended glob patterns.
setopt extendedglob
# Exclude hidden files when expanding globs, unless they explicitly start with a
# dot.
unsetopt globdots
# Remove superfluous blanks before recording entry.
setopt histreduceblanks
# No beeping
unsetopt beep
# No c-s/c-q output freezing
unsetopt flowcontrol
# Try to avoid the 'zsh: no matches found...'
unsetopt nomatch

#
# Path
#

# Ensure path arrays do not contain duplicates.
# shellcheck disable=2034
typeset -gU cdpath fpath mailpath manpath path

# Register user funcs and autoload them to make them callable. They can also be
# invoked as scripts.
# https://zsh.sourceforge.io/Intro/intro_4.html
# @todo load last, but need plugin helpers early
# shellcheck disable=2206
fpath=($XDG_CONFIG_HOME/shell/zsh/functions $fpath)
autoload -Uz "$XDG_CONFIG_HOME/shell/zsh/functions"/*(.:t)

#
# Instant prompt
#

# Activate direnv before instant prompt for compatibility, if a .env* file is
# present:
# https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-initialize-direnv-when-using-instant-prompt
# shellcheck disable=2144,2157
if iscmd direnv && [[ -n .env*(#q-.N) ]]; then
  direnv export zsh
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#
# @note tmux sessions should be created after instant prompt because tmux
# generates output to parent process:
# https://github.com/romkatv/powerlevel10k/issues/1203
#
# shellcheck disable=2296
source:file "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"

#
# Plugins
#

# zsh-autocomplete
source:file "$XDG_CONFIG_HOME/shell/zsh/zsh-autocomplete-rc.zsh"

source:file "$XDG_CONFIG_HOME/shell/zsh/load-plugins.zsh"
# Load p10k immediately after plugins for a fast prompt.
# https://github.com/romkatv/zsh-bench
source:file "$XDG_CONFIG_HOME/shell/zsh/p10k.zsh"
source:file "$XDG_CONFIG_HOME/shell/shellrc.sh"

# fzf
# https://thevaluable.dev/fzf-shell-integration/
source:file "$FZF_DIR/shell/completion.zsh" # @audit-ok
source:file "$FZF_DIR/shell/key-bindings.zsh" # @audit-ok
# source:file "$XDG_CONFIG_HOME/shell/zsh/fzf-tab-rc.zsh"

source:file "$XDG_CONFIG_HOME/shell/zsh/cdr.zsh"

# zoxide (load after compinit, fzf-rc, zsh-autocomplete)
eval:if-cmd zoxide zoxide init zsh # @audit-ok

# Load completions config last so it overrides settings from other plugins.
source:file "$XDG_CONFIG_HOME/shell/zsh/completions-rc.zsh"

# https://github.com/rothgar/mastering-zsh/blob/master/docs/helpers/widgets.md
autoload -Uz tetris tetriscurses

source:file "$XDG_CONFIG_HOME/shell/zsh/keybinds.zsh"
source:file "$XDG_CONFIG_HOME/shell/zsh/aliases.zsh"

eval:if-cmd direnv eval "$(direnv hook bash)"

# @note Uncomment the following line to print startup time.
# zprof
