#!/usr/bin/env bash

#
# ~/.bashrc: executed by bash for interactive non-login shells
#
#  - Sourced by .bash_profile so that it's loaded for all interactive shells
#    (similar to .zshrc)
#
# https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
#

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

# Load shared helpers (required by profile.sh).
rchelpers="${XDG_CONFIG_HOME:-$HOME/.config}/shell/helpers.sh"
# shellcheck disable=1090
if [ ! -r "$rchelpers" ] || ! source "$rchelpers"; then
    printf '[error] %s\n' "file not loaded: $rchelpers"
    return 1
fi
log:debug "file loaded: $rchelpers"
unset rchelpers

# Load shared shell environment (required by profile.sh).
source:file "$XDG_CONFIG_HOME/shell/env.sh"
# Load shared shell profile.
source:file "$XDG_CONFIG_HOME/shell/profile.sh"

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# Set variable identifying the chroot you work in (used in the prompt below).
if [[ -z ${debian_chroot:-} && -r /etc/debian_chroot ]]; then
    debian_chroot=$(</etc/debian_chroot)
fi

# Set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
xterm-color* | xterm-256color* | tmux*)
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    ;&
xterm* | rxvt*)
    # If this is an xterm set the title to user@host:dir
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*) PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ ' ;;
esac

#
# Completions
#

# brew
if ! shopt -oq posix; then
    source:file "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
fi

# gcloud
if [ -n "$HOMEBREW_PREFIX" ]; then
    source:file "$HOMEBREW_PREFIX/share/google-cloud-sdk/path.bash.inc"
    source:file "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.bash.inc"
fi

#
# Plugins
#

source:file "$XDG_CONFIG_HOME/shell/shellrc.sh"

# fzf
# https://thevaluable.dev/fzf-shell-integration/
source:file "$FZF_DIR/shell/completion.bash"   # @audit-ok
source:file "$FZF_DIR/shell/key-bindings.bash" # @audit-ok

# Use dircolors to set LS_COLORS to a nice theme (its output is the setter
# command).
#
# GNU ls (installed by brew as part of corutils on MacOS) uses LS_COLORS to
# colorize output. Here's a good reference:
# https://the.exa.website/docs/colour-themes
run:if-cmd gdircolors eval "$(gdircolors)"
