#!/usr/bin/env zsh
# shellcheck shell=bash

#
# ~/.zshrc: sourced by zsh in all interactive shells
#  - Login, non-login
#  - Should set up options, key bindings, functions, aliases, etc.
#
# Guides:
#  - https://zsh.sourceforge.io/Intro/intro_3.html
#  - https://zsh.sourceforge.io/Guide/zshguide02.html
#
# Examples:
#  - https://github.com/zsh-users/zsh/blob/master/StartupFiles/zshrc
#  - https://github.com/marlonrichert/zsh-launchpad/tree/main
#  - https://github.com/romkatv/zsh4humans/blob/v5/.zshrc
#  - https://github.com/romkatv/zsh4humans/blob/v5/.zshrc.mac
#

case $ZPROF_ENABLE in
1 | true) zmodload zsh/zprof ;;
esac

#
# Profile
#
# Load the shared shell profile here so it will be sourced in all interactive
# shells. ~/.zprofile is only loaded in login shells, so we don't use it.
#

# Load brew-shellenv first, which may be required by profile.sh.
_brew_shellenv="$XDG_CONFIG_HOME/shell/zsh/gen/brew-shellenv.zsh"
# shellcheck source=/dev/null
if [ -r "$_brew_shellenv" ] && ! source "$_brew_shellenv"; then
  printf '[warn] %s\n' "file not loaded: $_brew_shellenv" >&2
fi
_profile="$XDG_CONFIG_HOME/shell/profile.sh"
# shellcheck source=src/dot_config/shell/profile.sh
if [ ! -r "$_profile" ] || ! source "$_profile"; then
  printf '[error] %s\n' "file not loaded: $_profile" >&2
  return 1
fi
log:debug "file loaded: $_brew_shellenv"
log:debug "file loaded: $_profile"
unset _brew_shellenv _profile

#
# Options
#
#  - Should be set after loading plugins to avoid being overridden
#  - Reference: https://zsh.sourceforge.io/Doc/Release/Options.html
#  - Examples
#    - https://github.com/willghatch/zsh-saneopt/tree/master
#    - https://github.com/sorin-ionescu/prezto/tree/master/modules
#

# Correctly display UTF-8 with combining characters.
if [[ ${LC_CTYPE:-$LANG:u} == *UTF-8* ]]; then
  setopt combiningchars
fi

# Disable the log builtin so we don't conflict with /usr/bin/log, which is used
# for system logging on some OSes like MacOS.
disable log

export HISTSIZE=10000
export SAVEHIST=10000

# Use extended glob patterns.
setopt extendedglob
# Exclude hidden files when expanding globs, unless they explicitly start with a
# dot.
unsetopt globdots
# Remove superfluous blanks before recording entry.
setopt histreduceblanks
# No beeping
unsetopt beep
# No c-s/c-q output freezing
unsetopt flowcontrol
# Try to avoid the 'zsh: no matches found...'
unsetopt nomatch

#
# Path
#

# Ensure path arrays do not contain duplicates.
# shellcheck disable=2034
typeset -gU cdpath fpath mailpath manpath path

#
# Plugins
#

source:file "$XDG_CONFIG_HOME/shell/zsh/gen/load-plugins.zsh"

#
# Misc
#

# https://github.com/rothgar/mastering-zsh/blob/master/docs/helpers/widgets.md
autoload -Uz tetris tetriscurses

case $ZPROF_ENABLE in
1 | true) zprof ;;
esac
