#!/usr/bin/env zsh
# shellcheck shell=bash

#
# ~/.zshenv: sourced by zsh in all shells
#
#  - Should set the command search path and other important env vars
#  - Should not produce output or assume the shell is attached to a tty
#
# https://zsh.sourceforge.io/Intro/intro_3.html
#

# Disable global startup files because we set up everything manually:
# https://zsh.sourceforge.io/Doc/Release/Options.html
unsetopt globalrcs

# @todo only export with EXPORT
# unsetopt globalexport

# Load shared shell environment.
if [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh" ]; then
  # shellcheck source=src/dot_config/shell/env.sh
  source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"
fi

# Some plugins check this instead of $HOME
export ZDOTDIR="$HOME"
export ZPLUGINDIR="$XDG_DATA_HOME/zsh-plugins"

# This is the default path used by zsh-autocomplete. Don't name it ZSH_COMPDUMP
# because that triggers special logic for OMZ plugins, which we don't want.
export ZCOMPDUMP="$XDG_CACHE_HOME/zsh/compdump"
# Use the same path as zsh-autocomplete so the cache isn't duplicated if we
# decide to run compinit manually.
export ZCOMPCACHE="$XDG_CACHE_HOME/zsh/compcache"
