#!/usr/bin/env zsh
# shellcheck shell=bash

#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  if [[ -s $ZSH_COMPDUMP && (! -s "${ZSH_COMPDUMP}.zwc" || $ZSH_COMPDUMP -nt "${ZSH_COMPDUMP}.zwc") ]]; then
    if command mkdir "${ZSH_COMPDUMP}.zwc.lock" 2>/dev/null; then
      zcompile "$ZSH_COMPDUMP"
      command rmdir "${ZSH_COMPDUMP}.zwc.lock" 2>/dev/null
    fi
  fi
} &|
