#!/usr/bin/env bash

#
# ~/.bash_profile: executed by bash for interactive login shells
#
#  - Should not run any external commands or expensive operations because the
#    prompt and other plugins aren't set up yet
#
# https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
#

# Load .bashrc so login shells behave the same as non-login shells (it isn't
# sourced automatically by login shells).
# shellcheck disable=1091
if [ ! -r "$HOME/.bashrc" ] || ! source "$HOME/.bashrc"; then
    printf '[error] %s\n' "file not loaded: $HOME/.bashrc" >&2
    return 1
fi
