#!/usr/bin/env bash

#
# ~/.bash_profile: sourced by bash in interactive login shells
#
# https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
#

# Login shells don't source ~/.bashrc, and non-login shells don't source this
# file, so load ~/.bashrc here to make them behave the same.
if [ -r "$HOME/.bashrc" ]; then
    # shellcheck source=src/dot_bashrc
    source "$HOME/.bashrc"
fi
